gitea:
  ingress:
    enabled: true
    ingressClassName: "traefik"  # Usar Traefik como controlador de Ingress
    annotations:
      kubernetes.io/ingress.class: "traefik"
    hosts:
      - host: gitea.mabecenter.org  # El dominio donde se accederá a gitea
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: tls-cert  # Certificado TLS para la conexión segura
        hosts:
          - gitea.mabecenter.org
        
  gitea:
    admin:
      existingSecret: gitea-admin-secret

    config:
      storage:
        STORAGE_TYPE: "minio"
        MINIO_ENDPOINT: "minio.minio.svc.cluster.local:9000"
        MINIO_ACCESS_KEY_ID: "minioadmin"
        MINIO_SECRET_ACCESS_KEY: "minio123"
        MINIO_BUCKET: "gitea"
        MINIO_LOCATION: "us-east-1"
        MINIO_USE_SSL: false

  actions:
    enabled: true